name: Sandbox
version: '${project.version}'
main: be.mvpee.Main
api-version: '1.20'
load: STARTUP
authors: [mvpee]
website: www.mvpee.be
commands:
  contact:
    description: "How to contact me."
  help:
    description: "Display all commands."
  plugins:
    description: "Display the plugins (Github)."
  tools:
    description: "Tools menu for everyone."
  ping:
    description: "Display ping of the player."
  status:
    description: "Display all player and last connection."
  perm:
    description: "Change perms of a player"
