name: Sandbox
version: '1.0'
main: be.mvpee.Main
api-version: '1.20'
load: STARTUP
authors: [mvpee]
website: www.mvpee.be
commands:

  #MEMBER
  contact:
    description: "How to contact me."
  help:
    description: "Display all commands."
  plugins:
    description: "Display the plugins (Github)."
  tools:
    description: "Tools menu for everyone."
  ping:
    description: "Display ping of the player."
  money:
    description: "Display your balance."

  #STAFF
  # Admin
  status:
    description: "Display all player and information"
  moneygive:
    description: "Give money to a player"
  # Owner
  perm:
    description: "Change perms of a player"
